#!/usr/bin/env ruby
require 'nokogiri'
require 'date'

##
# This creates the header of our base html file.
#
# @param title   String the title for the page and main h1.
# @param chapter String name of the chapter.
# @return        String contains the header html.
def getHeader(title, chapter)
	return %Q{
<!DOCTYPE html>
<html>
	<head>
		<title>#{title}</title>
		<link href="../modules/style.css" type="text/css" rel="stylesheet"/>
		<script type="text/javascript" src="../modules/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="../modules/script.js"></script>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	</head>
	<body>
		<header>
			<form id="checkbox">
				<input type="button" name="testTake" value="Take Test" id="testTake"></input>
				<!--<label for="testTake">Take Test</label>-->
			</form>

			<h1>#{title}</h1>

			<form name="myForm" id="selectChapter">
				<select name="mySelect" onchange="gotoPage()">
				</select>
			</form>
		</header>

		<div class="grade">
			<div class="close">X</div>
			<h3>You Scored</h3>
			<p><span class="correct"></span>/<span class="total"></span> = <span class="answer"></span>%</p>
		</div>

		<h2 id="#{chapter.downcase.gsub(/\s*/, "")}">#{chapter}</h2>
		<!-- Ruby Header Ends -->
	}
end


##
# This creates the body of the html document.
#
# @param   file String contains the name of the file to create the html body from
# @return  noko String contains the content for the html document.
def getBody(file, chapter)
	f = File.open(file)
	# Modify html to work with our setup.
	noko = filterNoko(Nokogiri::HTML(f))
	f.close()

	return "\n<div class='chapter-questions #{chapter.downcase.gsub(/\s*/, "")}'>\n" + noko.to_html + "\n<div class='insert-questions' style='display:none;'></div></div>\n</div>\n"
end


##
# This creates the footer of the document.
# 
# @return String contains the footer html.
def getFooter()
	return %Q{
		<!-- Ruby Footer Starts -->
		<footer>Created By Ritchie Fitzgerald, Bryce, Richard Henke. Copyright &copy; #{Date.today.strftime("%Y")}</footer>
	</body>
</html>
	}
end


##
# This modifies the original html to work with our setup.
#
# @param  noko Nokogiri contains the nokogiri object that holds the original html.
# @return noko Nokogiri contains the nokogiri object that holds the modified html.
def filterNoko(noko)
	# Makes it easier for jquery to link to this element.
	noko.css(".examQuestionTable > tbody > tr:first-of-type > td:first-of-type img").each do |element|
		element["class"] = "question-image"
	end

	# We don't want to see the wrong answers initially.
	noko.css(".examAnswerTable img[src*=delete]").remove()

	# Modifies all the image paths to be correct, and we change all the error images into
	# the correct images.
	noko.css("img[src*=check], img[src*=delete]").each do |element|
		element["src"] = "../Images/check.png"
	end

	noko.css(".examQuestionSeparator").each do |n|
		n.unlink
	end

	return noko
end


##
# This takes all the html and removes anything that shouldn't be there.
#
# @param  doc_str String contains the original html file.
# @return         String the fixed html file
def create_doc(doc_str)
	doc_array = doc_str.split("\n")
	doc_array_mod = []
	doc_array.each do |line|
		if (line.include? "PUBLIC") or (line.include? "html" and line.include? "body") then next end
		doc_array_mod << line
	end

	return doc_array_mod.join("\n")
end


##
# Use this to insert new questions and create a new chapter.
#
# @param to      String the file to write to.
# @param from    String the file to read from.
# @param chapter String the name for the section of new questions.
# @return        String the new html file with the new questions inserted.
def insertChapter(to, from, chapter)
	fTo = File.open(to)
	fFrom = File.open(from)
	write_noko = Nokogiri::HTML(fTo)
	read_noko = filterNoko(Nokogiri::HTML(fFrom))
	write_noko.css(".insert-chapter").each do |node|
		node.replace "<h2 id='#{chapter.downcase.gsub(/\s*/, '')}'>#{chapter}</h2>\n<div class='chapter-questions #{chapter.downcase.gsub(/\s*/, '')}'>\n" + read_noko.to_html + "\n<div class='insert-questions' style='display:none;'></div>\n</div>\n<div class='insert-chapter' style='display:none;'></div>\n"
	end

	# remove duplicate questions.
	seen = Hash.new(0)
	write_noko.css(".examQuestionTable").each{|n| n.unlink if (seen[n.css(".exam_question_content")[0].to_html] += 1) > 1}

	fTo.close()
	fFrom.close()
	# puts write_noko.to_html
	return write_noko.to_html
end


##
# Use this to insert new questions into a chapter.
#
# @param to      String the file to write to.
# @param from    String the file to read from.
# @param chapter String the name for the section of new questions.
# @return        String the new html file with the new questions inserted.
def addToChapter(to, from, chapter)
	fTo = File.open(to)
	fFrom = File.open(from)
	write_noko = Nokogiri::HTML(fTo)
	read_noko = filterNoko(Nokogiri::HTML(fFrom))
	write_noko.css(".#{chapter.downcase.gsub(/\s*/, '')} .insert-questions").each do |node|
		node.replace read_noko.to_html + "\n<div class='insert-questions' style='display:none;'></div>\n"
	end

	# remove duplicate questions.
	seen = Hash.new(0)
	write_noko.css(".examQuestionTable").each{|n| n.unlink if (seen[n.css(".exam_question_content")[0].to_html] += 1) > 1}

	fTo.close()
	fFrom.close()
	# puts write_noko.to_html
	return write_noko.to_html
end


##
# Displays how to use the program.
#
def usage()
	puts
	puts "USAGE"
	puts "-----------------------------------"
	puts "First Usage: build_test <filename>.html <name-for-questions>"
	puts "Example:     build_test Test1.html \"Chapter 1\""
	puts
	puts "Insert Chapter: build_test <original-filename>.html -i <filename-more-questions>.html <name-for-questions>"
	puts "Example:        build_test Test1.html -i chapter2questions.html \"Chapter 2\""
	puts
	puts "Add Questions: build_test <original-filename>.html -a <filename-more-questions>.html <chapter-to-add-to>"
	puts "Example:       build_test Test1.html -a chapter2questions.html chapter2"
	puts
	puts "See Chapter ID's: build_test -pid <original-filename>.html"
	puts "Example:          build_test -pid Test1.html"
	puts "Output:           CHAPTER ID's"
	puts "                  ------------------"
	puts "                  chapter1"
	puts "                  chapter2"
	puts
	puts
	puts "Explanation"
	puts "-----------------------------------"
	puts "-i                    Means insert the following file into original file as a new chapter."
	puts "-a                    Means insert the following file into original file as an addition to a chapter."
	puts "-pid                  Prints the chapter ids so that you know how to add to them."
	puts "name-for-questions    Should always start with \"Chapt\" for the automatic jumping to work."
	puts "chapter-to-add-to     Must be a chapter ID. @see -pid"
	puts
end


##
# Runs code to create a working testing html file.
#
def main()
	if ARGV[0]
		# Do this if we are supposed to insert a new chapter with questions.
		if File.file?(ARGV[0]) and ARGV.any?{|arg| arg == "-i"} and File.file?(ARGV[2]) and ARGV[3]
			to = ARGV[0]
			from = ARGV[2]
			chapter = ARGV[3]

			# Add more questions to the base html file.
			doc = insertChapter(to, from, chapter)

			# Save new file.
			File.open(to, 'w'){|file| file.write(doc)}
			exit
		end

		# Do this if we are supposed to insert new questions into an old chapter.
		if File.file?(ARGV[0]) and ARGV.any?{|arg| arg == "-a"} and File.file?(ARGV[2]) and ARGV[3]
			to = ARGV[0]
			from = ARGV[2]
			chapter = ARGV[3]

			# Add more questions to the base html file.
			doc = addToChapter(to, from, chapter)

			# Save new file.
			File.open(to, 'w'){|file| file.write(doc)}
			exit
		end

		# Do this if we are building a new html file.
		if File.file?(ARGV[0]) and not ARGV.any?{|arg| arg == "-i"} and ARGV[1]
			file = ARGV[0]
			chapter = ARGV[1]
			title = File.basename(file, ".*")

			# Create Base HTML file.
			header = getHeader(title, chapter)
			body = getBody(file, chapter)
			footer = getFooter()
			doc = create_doc(header + body + "\n<div class='insert-chapter' style='display:none;'></div>\n" + footer)

			# Save file.
			File.open(file, 'w'){|f| f.write(doc)}
			exit
		end

		if ARGV.any?{|arg| arg == "-pid"} and File.file?(ARGV[1])
			chapters = Nokogiri::HTML(File.open(ARGV[1]))

			puts
			puts "CHAPTER ID's"
			puts "------------------------------"

			chapters.css("[id*=chapt]").each do |chapter|
				puts chapter["id"]
			end

			puts
			exit
		end

		usage()
	else
		usage()
	end
end

if __FILE__ == $0
	main()
end
