#!/usr/bin/env ruby
def read_newline_data(file_path)
    array = []
    File.open(file_path, "r").each_line{|line| array << line.strip}
    return array
end

if __FILE__ == $0
	if ARGV[0]
	    command = ARGV[0]
	    lines = read_newline_data(ARGV[1])

	    lines.each do |line|
	    	begin
	    		system "#{command} #{line}"
	    		puts "#{command} #{line}"
	    	rescue Exception => e
	    		puts "Error: While executing following command."
	    		puts "Command: #{command} #{line}"
	    	end	    	
	    end
    else
    	puts "Example Usage"
    	puts "-----------------------"
    	puts "repeat_command \"<command>\" <filename>"
    	puts
    	puts "repeat_command \"drush en \" drupal_modules.txt"
    	puts
    	puts "filename - must contain something on each line."
	end

end
